## Metadata for IBM Node.js sample configuration
## This metadata is used to augment the values.yaml file to drive the ICP UI for configuration of the Helm chart installation

## Image configuration metadata
image:
  __metadata:
    label: "Docker image configuration"
  repository:
    __metadata:
      name: "Repository"
      label: "Docker Repository"
      description: "Docker repository to pull image from."
      type: "string"
      immutable: true
      required: true

  tag:
    __metadata:
      name: "tag"
      label: "Docker image tag to use"
      description: "Determines the Node.js version."
      options: 
        label: "6"
        value: "6"
        label: "8"
        value: "8"

  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      type: "string"
      immutable: "true"
      required: true

## Service configuration metadata
service:
  __metadata:
    label: "Service configuration"
  name: 
    __metadata:
      name: "Name"
      label: "Service Name"
      description: "This is the Kubernetes service name: it must be letters and/or text for this sample."
      type: "string"
      immutable: "false"
      required: true
      validation: "^[a-zA-Z]([-a-zA-Z0-9])+$"
  type: 
    __metadata:
      name: "Type"
      label: "Service Type"
      description: "This is the Kubernetes service type: choose ClusterIP to only have the deployed sample accessible inside of your cluster, or via port forwarding. NodePort should be used if you want anyone who can access this IBM Cloud Private instance to view the application."
      type: "string"
      immutable: "false"
      required: true
      options:
        - label: "Node Port"
          value: "NodePort"
          value: "ClusterIP"
        - label: "Cluster IP"
  port:
    __metadata:
      name: "Port"
      label: "Port"
      description: "This is the port for the service and must match the Node.js listen server port number and what is exposed in the Dockerfile."
      type: "string"
      immutable: "true"
      required: true
